const dataBrown = [
  {
    id: "brown1",
    src: "url('./assets/MythicCards/brown/brown1.png')",
    difficulty: "normal",
    color: "brown",
  },
  {
    id: "brown2",
    src: "url('./assets/MythicCards/brown/brown2.png')",
    difficulty: "normal",
    color: "brown",
  },
  {
    id: "brown3",
    src: "url('./assets/MythicCards/brown/brown3.png')",
    difficulty: "normal",
    color: "brown",
  },
  {
    id: "brown4",
    src: "url('./assets/MythicCards/brown/brown4.png')",
    difficulty: "normal",
    color: "brown",
  },
  {
    id: "brown5",
    src: "url('./assets/MythicCards/brown/brown5.png')",
    difficulty: "normal",
    color: "brown",
  },
  {
    id: "brown6",
    src: "url('./assets/MythicCards/brown/brown6.png')",
    difficulty: "hard",
    color: "brown",
  },
  {
    id: "brown7",
    src: "url('./assets/MythicCards/brown/brown7.png')",
    difficulty: "hard",
    color: "brown",
  },
  {
    id: "brown8",
    src: "url('./assets/MythicCards/brown/brown8.png')",
    difficulty: "hard",
    color: "brown",
  },
  {
    id: "brown9",
    src: "url('./assets/MythicCards/brown/brown9.png')",
    difficulty: "hard",
    color: "brown",
  },
  {
    id: "brown10",
    src: "url('./assets/MythicCards/brown/brown10.png')",
    difficulty: "hard",
    color: "brown",
  },
  {
    id: "brown11",
    src: "url('./assets/MythicCards/brown/brown11.png')",
    difficulty: "easy",
    color: "brown",
  },
  {
    id: "brown12",
    src: "url('./assets/MythicCards/brown/brown12.png')",
    difficulty: "easy",
    color: "brown",
  },
  {
    id: "brown13",
    src: "url('./assets/MythicCards/brown/brown13.png')",
    difficulty: "easy",
    color: "brown",
  },
  {
    id: "brown14",
    src: "url('./assets/MythicCards/brown/brown14.png')",
    difficulty: "easy",
    color: "brown",
  },
  {
    id: "brown15",
    src: "url('./assets/MythicCards/brown/brown15.png')",
    difficulty: "normal",
    color: "brown",
  },
  {
    id: "brown16",
    src: "url('./assets/MythicCards/brown/brown16.png')",
    difficulty: "normal",
    color: "brown",
  },
  {
    id: "brown17",
    src: "url('./assets/MythicCards/brown/brown17.png')",
    difficulty: "normal",
    color: "brown",
  },
  {
    id: "brown18",
    src: "url('./assets/MythicCards/brown/brown18.png')",
    difficulty: "normal",
    color: "brown",
  },
  {
    id: "brown19",
    src: "url('./assets/MythicCards/brown/brown19.png')",
    difficulty: "normal",
    color: "brown",
  },
  {
    id: "brown20",
    src: "url('./assets/MythicCards/brown/brown20.png')",
    difficulty: "normal",
    color: "brown",
  },
  {
    id: "brown21",
    src: "url('./assets/MythicCards/brown/brown21.png')",
    difficulty: "easy",
    color: "brown",
  },
];

export default dataBrown;
